cluster-url: https://master.svil2.ocprm.testposte:8443
service-token-credential: OCP_SERVICE_TOKEN
git-credential: GIT_TOKEN
seed-job:
  git:
    url: https://github.com/ccangemi-redhat/test.git
    branch: master
    credential: GIT_TOKEN
  folder: core-jobs
applications:
  - name: feu-list
    namespace: feu-list
    git:
      url: http://gitlab.rete.poste/feu/lists.git
      branch:  test_jenkins2 
      credential: GIT_TOKEN
    auto-deploy: false
